import type { Metadata } from "next";
import "./globals.css";

// const spaceMono = Space_Mono({
//   weight: ["400", "700"],
//   subsets: ["latin"],
//   style: ["normal", "italic"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
